Repository Handsol/usenavidate, pull requests merged in 2025-03, with the labels that each got.

#11 ✨ Feat: 선택한 주소 리스트로 출력하기 구현
  src/pages/DateRouteWritePage.jsx
Labels: 🤘본승

#14 ✨ feat: ProfilePage 생성 및 라우터 연결
  src/pages/ProfilePage.jsx
  src/shared/Router.jsx
Labels: 🍊나현

#13 Feature/writepost
  package.json
  src/assets/img-plus.png
  src/pages/WritePostPage.jsx
  yarn.lock
Labels: 🍀록기

#16 feat: 지도 범위 재설정
  src/pages/DateRouteWritePage.jsx
Labels: 🤘본승

#17 ✨ Feat: zustand AuthStore 생성
  src/App.jsx
  src/zustand/AuthStore.js
Labels: 🍊나현

#18 :lipstick: Style: 헤더 일부 UI 수정 / 로그인 페이지 UI 구현 완료 / 회원가입 페이지 UI 구현 완료
  src/App.jsx
  src/index.css
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
Labels: 🐈‍⬛도현

#19 ✨ Feat: ImageInput- supabase 업로드 연결
  src/components/ImageInput.jsx
  src/pages/ProfilePage.jsx
Labels: 🍊나현

#20 ✨ Feat : 네비톡 페이지, 메인 페이지 리스트 정보 불러오기 (Supabase 연결)
  src/components/DateRoutePost.jsx
  src/components/NaviTalkPost.jsx
  src/components/PostList.jsx
  src/components/Search.jsx
  src/pages/DateRoutePage.jsx
  src/pages/NaviTalkPage.jsx
  src/pages/detail/NaviTalkDetail.jsx
Labels: 🪄한솔

#21 ✨ Feat: 키워드 검색 기능 구현
  src/pages/DateRouteWritePage.jsx
  src/pages/WritePostPage.jsx
Labels: 🤘본승

#24 [Feature] 게시글 작성 기능 태그 dropdown 구현
  src/components/Comment.jsx
  src/data/categoryData.js
  src/pages/WritePostPage.jsx
Labels: 🍀록기

#26 ✨ Feat : 네비톡 디테일 페이지 연결 리스트 정보 불러오기 (Supabase 연결)
  package.json
  public/navi_talk_default.png
  public/write_post_logo.png
  public/write_post_plus.png
  src/components/DateRoutePost.jsx
  src/components/NaviTalkPost.jsx
  src/components/PostList.jsx
  src/pages/DateRoutePage.jsx
  src/pages/NaviTalkPage.jsx
  src/pages/detail/NaviTalkDetail.jsx
  src/shared/PATH.js
  src/shared/Router.jsx
  yarn.lock
Labels: 🪄한솔

#27 🩹 Fix: MyPage 내용 수정
  src/components/layout/Header.jsx
  src/pages/MyPage.jsx
Labels: 🍊나현

#32 ✨ Feat : supabase 기능 이미지, 상세, 가게이름 etc
  src/pages/WritePostPage.jsx
Labels: 🍀록기

#36 ✨ Feat : 검색 기능 구현
  src/components/Search.jsx
  src/pages/SearchPage.jsx
  src/shared/PATH.js
  src/shared/Router.jsx
Labels: 🪄한솔

#35 🩹 Fix: ProfilePage 내 profileform 분리 , supabase 연결
  src/components/ImageInput.jsx
  src/components/ProfileForm.jsx
  src/pages/ProfilePage.jsx
Labels: 🍊나현

#37 ♻️ Refactor : 네비톡 코드 리팩토링(커스텀 훅 추가, 게시글 수정/삭제 기능 추가)
  src/components/PostEditDropdown.jsx
  src/components/ProtectRoute.jsx
  src/hooks/useAuthUser.js
  src/hooks/useFetchPostDetail.js
  src/hooks/useFetchPosts.js
  src/pages/DateRoutePage.jsx
  src/pages/NaviTalkPage.jsx
  src/pages/detail/NaviTalkDetail.jsx
  src/supabase/SupabaseAuth.js
Labels: 🪄한솔

#43 ✨ Feat: 게시글 삭제 기능 구현
  src/components/PostEditDropdown.jsx
  src/pages/DateRouteWritePage.jsx
  src/pages/detail/DateRouteDetail.jsx
  src/utils/DeletePost.js
Labels: 🤘본승

#42 🩹Fix: profile 오류 수정
  src/components/ImageInput.jsx
  src/components/ProfileForm.jsx
  src/pages/ProfilePage.jsx
Labels: 🍊나현
